### ISSUE TITLE
Can't import skflow or run tutorials

### ISSUE THREAD

**Issue by HamedMP** [google/skflow#4]
Great effort by Google to simplify using TensorFlow.
I use command 
    `pip install git+git://github.com/google/skflow.git`
to install it on my Mac OS 10.11 inside a VirtualEnv where the TF is also installed there, but I can't import the skflow
I checked V.Env python `site-packages` and the `skflow` folder is there. 

Will be happy if I can test it, because I'm also eager to provide a wrapper for TF and I want to join this Library. 

```python
>>> import skflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "skflow.py", line 15, in <module>
    classifier = skflow.TensorFlowDNNClassifier(hidden_units=[10, 20, 10],
AttributeError: 'module' object has no attribute 'TensorFlowDNNClassifier'

```

**Comment by HamedMP** [comment]
I found out that when I import it from python in terminal, without being into any project it works. After some time I understand that I named the file also skflow.py and It tries to import itself and can't find the method `TensorFlowDNNClassifier` which cause the error.
