### ISSUE TITLE
Error while running text_classification*

### ISSUE THREAD

**Issue by melvinj** [google/skflow#72]
Hi,

I'm trying to run the text_classification examples and I get the following error.

TypeError: Input 'values' of 'HistogramSummary' Op has type int64 that does not match expected type of float32.

The stack trace is below:

Traceback (most recent call last):
  File "text_classification.py", line 82, in <module>
    classifier.fit(X_train, y_train, logdir='/tmp/tf_examples/word_rnn')
  File "/usr/local/lib/python2.7/site-packages/skflow/estimators/base.py", line 186, in fit
    self._setup_training()
  File "/usr/local/lib/python2.7/site-packages/skflow/estimators/base.py", line 119, in _setup_training
    tf.histogram_summary("X", self._inp)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/summary_ops.py", line 39, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 34, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 405, in apply_op
    (prefix, types_lib.as_dtype(input_arg.type).name))
TypeError: Input 'values' of 'HistogramSummary' Op has type int64 that does not match expected type of float32.

Am I doing something wrong? I installed tensorflow and skflow as mentioned in the medium tutorial.

**Comment by ilblackdragon** [comment]
Hi,

Weirdly I don't get this error, but I've updated histogram addition only for float.
Please try with the current master if it now works for you. Let me know if it works now.

**Comment by melvinj** [comment]
Hi,
It works now. Thanks for the very prompt response.
